// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_calcEmis
List rcpp_calcEmis(const NumericVector cta, const NumericVector a0a, const NumericVector u0a, const NumericVector r1a, const NumericVector r2a, const NumericVector r3a, const NumericVector f4a, const NumericVector r5a, const IntegerVector gstart, const IntegerVector gend);
RcppExport SEXP _ALFAM2_rcpp_calcEmis(SEXP ctaSEXP, SEXP a0aSEXP, SEXP u0aSEXP, SEXP r1aSEXP, SEXP r2aSEXP, SEXP r3aSEXP, SEXP f4aSEXP, SEXP r5aSEXP, SEXP gstartSEXP, SEXP gendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type cta(ctaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type a0a(a0aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type u0a(u0aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r1a(r1aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r2a(r2aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r3a(r3aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type f4a(f4aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r5a(r5aSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type gstart(gstartSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type gend(gendSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calcEmis(cta, a0a, u0a, r1a, r2a, r3a, f4a, r5a, gstart, gend));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ALFAM2_rcpp_calcEmis", (DL_FUNC) &_ALFAM2_rcpp_calcEmis, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_ALFAM2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
