// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_calcEmis
List rcpp_calcEmis(const NumericVector ct, const double a0, const double u0, const NumericVector r1, const NumericVector r2, const NumericVector r3, const NumericVector f4);
RcppExport SEXP _ALFAM2_rcpp_calcEmis(SEXP ctSEXP, SEXP a0SEXP, SEXP u0SEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP r3SEXP, SEXP f4SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< const double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< const double >::type u0(u0SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r3(r3SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type f4(f4SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calcEmis(ct, a0, u0, r1, r2, r3, f4));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ALFAM2_rcpp_calcEmis", (DL_FUNC) &_ALFAM2_rcpp_calcEmis, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ALFAM2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
