# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calcEmis <- function(cta, F0a, S0a, r1a, r2a, r3a, f4a, r5a, gstart, gend) {
    .Call('_ALFAM2_rcpp_calcEmis', PACKAGE = 'ALFAM2', cta, F0a, S0a, r1a, r2a, r3a, f4a, r5a, gstart, gend)
}

