# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calcEmis <- function(ct, a0, u0, r1, r2, r3, f4) {
    .Call('_ALFAM2_rcpp_calcEmis', PACKAGE = 'ALFAM2', ct, a0, u0, r1, r2, r3, f4)
}

